/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chart/{kind}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chart
         * @description Word 보고서에 들어가는 것과 **같은** PNG 를 돌려준다.
         *
         *     화면 차트를 recharts 로 따로 그리면 사용자가 본 그림과 문서에 실리는
         *     그림이 갈라진다. Streamlit 판은 같은 PNG 를 화면과 문서가 공유했고
         *     ("5종 차트를 확인하세요. 보고서에 그대로 삽입됩니다"), 그 계약을 지킨다.
         *
         *     추이 차트만은 화면에서 인터랙티브(recharts)로도 보여준다 — 값을 짚어
         *     읽는 용도다. 나머지 4종은 이 PNG 가 유일한 표현이다.
         */
        get: operations["get_chart_api_chart__kind__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Info */
        get: operations["get_dataset_info_api_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Narrative */
        post: operations["post_narrative_api_narrative_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Regions */
        get: operations["get_regions_api_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Report */
        post: operations["post_report_api_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Api Key */
        post: operations["set_api_key_api_settings_api_key_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Stats */
        post: operations["post_stats_api_stats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Region Universities
         * @description 권역 안의 대학 전체와 그 해 지표.
         *
         *     비교군 후보를 고르는 화면과 권역 막대차트가 같은 데이터를 쓴다.
         *     `/api/stats` 의 `compare` 는 **확정된 비교군만** 담으므로, 후보를 보여주려면
         *     이게 따로 필요하다.
         */
        get: operations["get_region_universities_api_universities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyRequest */
        ApiKeyRequest: {
            /** Apikey */
            apiKey: string;
        };
        /**
         * Averages
         * @description 한 해의 평균 3종. 모집단이 비면 0.0 이 아니라 None 이다.
         */
        Averages: {
            /** Comparegroup */
            compareGroup: number | null;
            /** National */
            national: number | null;
            /** Regional */
            regional: number | null;
        };
        /**
         * CompareRow
         * @description 비교군 표의 한 행.
         */
        CompareRow: {
            /** Faculty */
            faculty: number;
            /** Name */
            name: string;
            /** Nationalrank */
            nationalRank: number | null;
            /** Papers */
            papers: number;
            /** Percapita */
            perCapita: number;
            /** Regionalrank */
            regionalRank: number | null;
        };
        /**
         * DatasetInfo
         * @description 어떤 데이터로 계산했는지. 화면 라벨의 근거가 된다.
         */
        DatasetInfo: {
            /** Nationalrankscopenote */
            nationalRankScopeNote: string;
            /** Regions */
            regions: string[];
            /** Universities */
            universities: string[];
            /** Universitycount */
            universityCount: number;
            /** Years */
            years: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NarrativeRequest */
        NarrativeRequest: {
            /** Comparegroup */
            compareGroup?: string[] | null;
            /** Keys */
            keys?: string[] | null;
            /** Regionname */
            regionName?: string | null;
            /** University */
            university: string;
            /** Year */
            year: number;
        };
        /**
         * NarrativeResponse
         * @description 생성된 서술.
         *
         *     키가 4종 전부 오지 않을 수 있다 — 일부만 요청했거나, 일부만 실패했을 때다.
         *     `failed` 에 실패한 키와 이유를 담는다. 조용히 빈 문자열을 돌려주면
         *     사용자는 GPT 가 "아무 말도 하지 않았다" 고 오해한다.
         */
        NarrativeResponse: {
            /** Failed */
            failed: {
                [key: string]: string;
            };
            /** Narratives */
            narratives: {
                [key: string]: string;
            };
        };
        /**
         * RankChange
         * @description 순위와 그 변화.
         *
         *     **부호 규약: 양수 = 개선.** 순위는 작아지는 것이 개선이므로
         *     `이전순위 - 현재순위` 다. V09 가 이 규약을 화면에서 한 번 더 뒤집어
         *     개선을 하락으로 표시했던 결함이다. 여기서 못박고 프론트는 그대로 쓴다.
         */
        RankChange: {
            /** Nationalrank */
            nationalRank: number | null;
            /** Nationalrankdelta */
            nationalRankDelta: number | null;
            /** Regionalrank */
            regionalRank: number | null;
            /** Regionalrankdelta */
            regionalRankDelta: number | null;
        };
        /**
         * RegionsResponse
         * @description 대학이 속한 권역들. 다중 캠퍼스는 2개 이상이 나온다.
         */
        RegionsResponse: {
            /** Regions */
            regions: string[];
            /** University */
            university: string;
        };
        /** ReportRequest */
        ReportRequest: {
            /** Comparegroup */
            compareGroup?: string[] | null;
            /** Narratives */
            narratives?: {
                [key: string]: string;
            };
            /** Regionname */
            regionName?: string | null;
            /** University */
            university: string;
            /** Year */
            year: number;
        };
        /**
         * SettingsResponse
         * @description 서버 설정 상태.
         *
         *     **키 값 자체는 절대 담지 않는다.** 브라우저로 내려가면 개발자 도구에
         *     그대로 보인다. 설정됐는지와 어떻게 설정됐는지만 알린다.
         */
        SettingsResponse: {
            /** Apikeyconfigured */
            apiKeyConfigured: boolean;
            /** Apikeyhint */
            apiKeyHint: string | null;
            /** Apikeysource */
            apiKeySource: string | null;
            /** Canpersist */
            canPersist: boolean;
        };
        /** StatsRequest */
        StatsRequest: {
            /** Comparegroup */
            compareGroup?: string[] | null;
            /** Regionname */
            regionName?: string | null;
            /** University */
            university: string;
            /** Year */
            year: number;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Averages */
            averages: {
                [key: string]: components["schemas"]["Averages"];
            };
            /** Compare */
            compare: components["schemas"]["CompareRow"][];
            /** Comparegroup */
            compareGroup: string[];
            /** Comparegroupnote */
            compareGroupNote: string | null;
            /** Rankchanges */
            rankChanges: {
                [key: string]: components["schemas"]["RankChange"];
            };
            /** Regionname */
            regionName: string;
            /** Trend */
            trend: {
                [key: string]: components["schemas"]["TrendPoint"];
            };
            /** University */
            university: string;
            /** Year */
            year: number;
            yoy: components["schemas"]["YoYChanges"];
        };
        /**
         * TrendPoint
         * @description 한 해의 대상 대학 실적.
         */
        TrendPoint: {
            /** Faculty */
            faculty: number;
            /** Nationalrank */
            nationalRank: number | null;
            /** Papers */
            papers: number;
            /** Percapita */
            perCapita: number;
            /** Regionalrank */
            regionalRank: number | null;
        };
        /**
         * UniversitiesResponse
         * @description 권역 안의 대학 전체. 비교군 후보 선택과 권역 막대차트가 함께 쓴다.
         */
        UniversitiesResponse: {
            /** Regionname */
            regionName: string;
            /** Rows */
            rows: components["schemas"]["UniversityRow"][];
            /** Year */
            year: number;
        };
        /**
         * UniversityRow
         * @description 권역 대학 한 곳의 그 해 지표.
         */
        UniversityRow: {
            /** Faculty */
            faculty: number;
            /** Name */
            name: string;
            /** Nationalrank */
            nationalRank: number | null;
            /** Papers */
            papers: number;
            /** Percapita */
            perCapita: number;
            /** Regionalrank */
            regionalRank: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** YoYChanges */
        YoYChanges: {
            /** Bottom */
            bottom: components["schemas"]["YoYEntry"][];
            target: components["schemas"]["YoYEntry"] | null;
            /** Top */
            top: components["schemas"]["YoYEntry"][];
        };
        /**
         * YoYEntry
         * @description 전년 대비 증감 한 건.
         */
        YoYEntry: {
            /** Basevalue */
            baseValue: number;
            /** Changerate */
            changeRate: number | null;
            /** Comparevalue */
            compareValue: number;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_chart_api_chart__kind__png_get: {
        parameters: {
            query: {
                university: string;
                year: number;
                region?: string | null;
                /** @description 비교군 대학 이름. **반드시 보고서와 같은 값을 보내야 한다** — 생략하면 서버 기본 비교군으로 그려져 Word 와 그림이 달라진다. */
                compareGroup?: string[] | null;
            };
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_info_api_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfo"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    post_narrative_api_narrative_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NarrativeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regions_api_regions_get: {
        parameters: {
            query: {
                university: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_report_api_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    set_api_key_api_settings_api_key_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_stats_api_stats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_region_universities_api_universities_get: {
        parameters: {
            query: {
                region: string;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
