/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Info */
        get: operations["get_dataset_info_api_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Regions */
        get: operations["get_regions_api_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Stats */
        post: operations["post_stats_api_stats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spa */
        get: operations["spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Averages
         * @description 한 해의 평균 3종. 모집단이 비면 0.0 이 아니라 None 이다.
         */
        Averages: {
            /** Comparegroup */
            compareGroup?: number | null;
            /** National */
            national?: number | null;
            /** Regional */
            regional?: number | null;
        };
        /**
         * CompareRow
         * @description 비교군 표의 한 행.
         */
        CompareRow: {
            /** Faculty */
            faculty: number;
            /** Name */
            name: string;
            /** Nationalrank */
            nationalRank?: number | null;
            /** Papers */
            papers: number;
            /** Percapita */
            perCapita: number;
            /** Regionalrank */
            regionalRank?: number | null;
        };
        /**
         * DatasetInfo
         * @description 어떤 데이터로 계산했는지. 화면 라벨의 근거가 된다.
         */
        DatasetInfo: {
            /** Nationalrankscopenote */
            nationalRankScopeNote: string;
            /** Regions */
            regions: string[];
            /** Universitycount */
            universityCount: number;
            /** Years */
            years: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RankChange
         * @description 순위와 그 변화.
         *
         *     **부호 규약: 양수 = 개선.** 순위는 작아지는 것이 개선이므로
         *     `이전순위 - 현재순위` 다. V09 가 이 규약을 화면에서 한 번 더 뒤집어
         *     개선을 하락으로 표시했던 결함이다. 여기서 못박고 프론트는 그대로 쓴다.
         */
        RankChange: {
            /** Nationalrank */
            nationalRank?: number | null;
            /** Nationalrankdelta */
            nationalRankDelta?: number | null;
            /** Regionalrank */
            regionalRank?: number | null;
            /** Regionalrankdelta */
            regionalRankDelta?: number | null;
        };
        /**
         * RegionsResponse
         * @description 대학이 속한 권역들. 다중 캠퍼스는 2개 이상이 나온다.
         */
        RegionsResponse: {
            /** Regions */
            regions: string[];
            /** University */
            university: string;
        };
        /** StatsRequest */
        StatsRequest: {
            /** Comparegroup */
            compareGroup?: string[] | null;
            /** Regionname */
            regionName?: string | null;
            /** University */
            university: string;
            /** Year */
            year: number;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Averages */
            averages: {
                [key: string]: components["schemas"]["Averages"];
            };
            /** Compare */
            compare: components["schemas"]["CompareRow"][];
            /** Comparegroup */
            compareGroup: string[];
            /** Comparegroupnote */
            compareGroupNote?: string | null;
            /** Rankchanges */
            rankChanges: {
                [key: string]: components["schemas"]["RankChange"];
            };
            /** Regionname */
            regionName: string;
            /** Trend */
            trend: {
                [key: string]: components["schemas"]["TrendPoint"];
            };
            /** University */
            university: string;
            /** Year */
            year: number;
            yoy: components["schemas"]["YoYChanges"];
        };
        /**
         * TrendPoint
         * @description 한 해의 대상 대학 실적.
         */
        TrendPoint: {
            /** Faculty */
            faculty: number;
            /** Nationalrank */
            nationalRank?: number | null;
            /** Papers */
            papers: number;
            /** Percapita */
            perCapita: number;
            /** Regionalrank */
            regionalRank?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** YoYChanges */
        YoYChanges: {
            /** Bottom */
            bottom?: components["schemas"]["YoYEntry"][];
            target?: components["schemas"]["YoYEntry"] | null;
            /** Top */
            top?: components["schemas"]["YoYEntry"][];
        };
        /**
         * YoYEntry
         * @description 전년 대비 증감 한 건.
         */
        YoYEntry: {
            /** Basevalue */
            baseValue: number;
            /** Changerate */
            changeRate?: number | null;
            /** Comparevalue */
            compareValue: number;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dataset_info_api_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfo"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_regions_api_regions_get: {
        parameters: {
            query: {
                university: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_stats_api_stats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
